### ISSUE TITLE
Vite complains that big integer literals are not available in target environment.

### ISSUE THREAD

**Issue by mdrie** [StaticJsCMS/static-cms#100]
When bundling static-cms with vite and starting the dev server, vite complains with
```log
Big integer literals are not available in the configured target environment ("chrome87", "edge88", "es2020", "firefox78", "safari13" + 2 overrides)
```

Minimal test project: https://github.com/mdrie/static-cms-vite
Run
```sh
npm ci
npm run cms:serve
```

Full output (from Windows) is also included n the README.md.

**Comment by Greenheart** [comment]
This will likely be resolved if you uodate to Vite 4, since the target Safari version was increased.

If that resolves ir, feel free to close this issue :)

**Comment by KaneFreeman** [comment]
Were you able to resolve this issue?

**Comment by mdrie** [comment]
I am sorry, but I did not have time to try.
