### ISSUE TITLE
[v4 beta] I18n side panel can't scroll

### ISSUE THREAD

**Issue by ddorstijn** [StaticJsCMS/static-cms#1002]
![afbeelding](https://github.com/StaticJsCMS/static-cms/assets/1730282/8e7c1873-08f4-4f52-8b6f-b0d2bc3468ad)

The CMS_Editor_i18n-panel has a style property that sets overflow to hidden, causing an inability to scroll. Changing this style into `overflow-y: scroll` fixes this.

**Comment by KaneFreeman** [comment]
This is resolved in `v4.0.0-beta.13`
