### ISSUE TITLE
[v4] `media_library` config not inherited from global

### ISSUE THREAD

**Issue by denyskon** [StaticJsCMS/static-cms#1004]
If I set a global `media_libary` config, e. g.
```js
media_library: {
  folder_support: true,
}
```
this config is not being inherited by the widgets, so I have to set it manually in every widget like image, file or markdown.

**Comment by KaneFreeman** [comment]
This is fixed in `v4.0.0-beta.14`

**Comment by KaneFreeman** [comment]
This is fixed in `v4.0.0-beta.15`
