### ISSUE TITLE
Bypass client side authentication

### ISSUE THREAD

**Issue by kylesloper** [StaticJsCMS/static-cms#1006]
Hi, I've set up my app so that authentication is done server side before reaching the CMS client. Since the CMS auth is now redundant, how can I configure the CMS to bypass the client side auth.

I'm using the git-gateway backend. Completely understand if this is something not wanted in the repo but I'd appreciate some guidance to get there myself.

Thanks for the great project :)

**Comment by denyskon** [comment]
Does your Git* Server not have authentication, or how is the CMS supposed to connect to it?

**Comment by kylesloper** [comment]
Everything works as normal with git-gateway & Git. Just wondered if there was something I could do to bypass the Netlify Identity auth that happens client side. 

Unless of course it is Netlify Identity that handles the connection to the Github repo.

It's honestly just a UX motion, might be the only solution to programmatically input a generic user and password and sign into Identity that way.

:)

**Comment by denyskon** [comment]
In this case, Netlify handles the GitHub repo auth

**Comment by KaneFreeman** [comment]
Git gateway with Netlify requires the use of the Netlify Identity login. There is no way to bypass that.
