### ISSUE TITLE
Ui widget is hidden on Mobile view 

### ISSUE THREAD

**Issue by sanabel-al-firdaws** [StaticJsCMS/static-cms#1011]
the mobile UI is great but when you add many widgets the last widget dosen't show up and you can't scrool down to see it

tested this on on edge for andriod the latest version

![Screenshot_20231226_002810](https://github.com/StaticJsCMS/static-cms/assets/136203274/689ee3d0-e583-473a-88be-7aa3c694ac27)

![Screenshot_20231226_002348](https://github.com/StaticJsCMS/static-cms/assets/136203274/0b6479a4-21d8-4d09-852d-f506f300f506)
![Screenshot_20231226_002407_com kiwibrowser browser](https://github.com/StaticJsCMS/static-cms/assets/136203274/51f8b565-791e-402b-9ad5-f37eada91a12)

(also tried clicking the flipped " ^ " button it dosen't help )

**Comment by abdullhakim-sami** [comment]
I am using kiwi browser in andriod and it has dev tools and chrome extensions i used stylus extension to change the css on my side its a temp fix and its just adding padding to all widgets

![Screenshot_20231226_005119_com kiwibrowser browser](https://github.com/StaticJsCMS/static-cms/assets/136203274/70569fd6-49f3-4b60-b750-d1f3e1be1e87)
![Screenshot_20231226_005137](https://github.com/StaticJsCMS/static-cms/assets/136203274/aef45688-7fbe-4685-8361-8612166efacd)
