### ISSUE TITLE
How do I get it up and running with Bitbucket as the GitHost and deployment on custom server ?

### ISSUE THREAD

**Issue by AnimeshRy** [StaticJsCMS/static-cms#1015]
Tried doing with decap but it seemed really difficult to set it up standalone with bitbucket as a githost. Is there an option to do this with static ?

**Comment by KaneFreeman** [comment]
It is possible, but not yet well documented. Issue #48 is open to work on the documentation for it.

Github and Bitbucket need a server side process to handle authentication, which in the default setup Netlify handles for you. To use a different hosting provider you need to host a server side OAuth function yourself that replaces the part Netlify usually handles. There is a working example for Github authentication (see https://github.com/StaticJsCMS/static-cms-next-vercel-template), but not one for Bitbucket yet. However the two setups should be very similar.

I am going to close this issue in favor of #48.

**Comment by AnimeshRy** [comment]
I'm currently using docusaurus with bitbucket (decap) but the implicit grant flow times out every 2 hours causing me to lose data if a person is still activily using the thing for a long time. Did you guys solve this issue here ? Can you also point me to a resource of how I can self host static cms as well and not use the cdn ?
