### ISSUE TITLE
Bug: Site URL link image in the UI overflows when the link has hyphen in it

### ISSUE THREAD

**Issue by dallyh** [StaticJsCMS/static-cms#1040]
Hello,

the title says it all, this is just a nuance, but the buttons under the Site URL link are not clickable in this case.

With hypen in the `deploy-previews` segment:

![image](https://github.com/StaticJsCMS/static-cms/assets/6968534/6e22aeec-3f06-4e54-9a34-7d62be62cf74)

Without hyphen:
![image](https://github.com/StaticJsCMS/static-cms/assets/6968534/cd016c6e-1557-4934-ab49-26e13fd7093e)

**Comment by KaneFreeman** [comment]
This is fixed in `v4.0.1`
