### ISSUE TITLE
DateTime field - default value of `""` (empty string) and `required: false` causes the field to have datetime format mask inside it

### ISSUE THREAD

**Issue by dallyh** [StaticJsCMS/static-cms#1051]
Hello,

when there is a DateTime field in a collection, and the field is set like this:

```json
        {
          "name": "modDatetime",
          "label": "Modified Date",
          "widget": "datetime",
          "i18n": "duplicate",
          "required": false,
          "date_format": true,
          "time_format": true,
          "default": ""
        },
```

Then in the UI, when a new entry is created, the field is filled with datetime format mask:
![image](https://github.com/StaticJsCMS/static-cms/assets/6968534/bef32ade-9409-4df1-a2b8-6f6b91ae4ed4)

This started happening on version 4.0.0, previous versions were fine. When an entry like this is saved, actual field has `""` (empty string) inside it, so just looks like a UI issue.

**Comment by KaneFreeman** [comment]
What you are seeing is only a placeholder and is not actually saved. It is simply how the MUI datepicker works in the most recent version. Addressing this would require replacing MUI as the component library we use for datepickers, which is not something we are looking to do.
