### ISSUE TITLE
Astro integration suddenly results to /admin 404

### ISSUE THREAD

**Issue by theN3rdson** [StaticJsCMS/static-cms#1078]
Hello. I got StaticCMS working on Astro for several days, all great, until this morning that it gave me a 404. Used static-cms 3.0.0 from CDN, also tried with 4.1.0 just now but same error.  Anyone have a clue or similar experience?
![image](https://github.com/StaticJsCMS/static-cms/assets/158120827/baed7be1-8f46-41fc-9922-9a58df3e3bba)

**Comment by oliverpool** [comment]
Did you try visiting `/admin/index.html` ?

**Comment by KaneFreeman** [comment]
This would be a better question for the Discord server. I have never used Astro, but some there might have.
