### ISSUE TITLE
Editorial Workflow Templates

### ISSUE THREAD

**Issue by KaneFreeman** [StaticJsCMS/static-cms#17]
Provide templates for an editorial workflow similar to [Netlify CMS](https://www.netlifycms.org/docs/beta-features/#gitlab-and-bitbucket-editorial-workflow-support)

**Comment by r-angeles** [comment]
Hi! I was looking through for some alternatives on NetlifyCMS and whilst researching, I stumbled on this discussion at TinaCMS [https://github.com/tinacms/tinacms/discussions/2962](https://github.com/tinacms/tinacms/discussions/2962). I believe their discussions on an editorial workflow is worth a look.

**Comment by KaneFreeman** [comment]
Netlify CMS also dealt with this by using branching (and PRs), but in doing so nearly doubled the code needed for EACH backend, and not every backend could support it.

In my opinion editorial workflow and preview deployments are outside of the scope of this project (at least at current with the size of the community and the number of maintainers).

However, this does not mean a similar setup cannot be achieved with how the CMS is today. I've just completed a template showing exactly that. A two environment setup with `draft` posts not appearing in the `production` build, but showing in the `staging` build.

https://github.com/StaticJsCMS/static-cms-next-netlify-editoral-template
