### ISSUE TITLE
Dependent Fields

### ISSUE THREAD

**Issue by Mario8419** [StaticJsCMS/static-cms#188]
Are you planning to show and hide fields depending on some other field values. for e.g a selected value?

**Comment by Mario8419** [comment]
[](https://github.com/netlify/netlify-cms/issues/565)

**Comment by leomp12** [comment]
+1 here 🤞🏾 
this is a feature I really missed in Netlify CMS, saw this _Conditional_ (without much documentation yet) on Keystatic https://thinkmill.notion.site/Fields-API-c0f928e38c304daf9b2929a97e36541f

**Comment by SergeyRe** [comment]
+2 nice  feature to realize

**Comment by leomp12** [comment]
I guess it can be closed https://www.staticcms.org/docs/widgets#field-conditions 👏🏾
