### ISSUE TITLE
Website Revitalization

### ISSUE THREAD

**Issue by KaneFreeman** [StaticJsCMS/static-cms#20]
- [x] Clean up documentation after rewrite
   - [x] Intro
   - [x] Account Settings - _Renamed Backends_
   - [x] Configure Your Site
   - [x] Collections
   - [x] Widgets
   - [x] Media
   - [x] Platform Guides - _Will review these after the beta release_ #72 
   - [x] Customizing Static CMS
   - [x] Community
- [x] Migrate site to NextJS
       The thought process here is mostly around my familiarity with NextJS vs Gatsby (which the current site uses). Both are fine choices. The website needs to be rewritten anyways in TypeScript, so this is as good as time as any to convert it.
- [x] Switch to Material UI
- [x] Mobile view
- [x] Search

**Comment by KaneFreeman** [comment]
#49

**Comment by HeyITGuyFixIt** [comment]
Not sure where you are at with this, but the mobile view needs some TLC.

**Comment by KaneFreeman** [comment]
Yup hadn't even started to look at the mobile view yet 😄

**Comment by KaneFreeman** [comment]
> Not sure where you are at with this, but the mobile view needs some TLC.

Should be fully responsive now. Let me know if you notice any issues with it in mobile.
