### ISSUE TITLE
Test and fix any issues with Commit Message Templates in the app and docs

### ISSUE THREAD

**Issue by KaneFreeman** [StaticJsCMS/static-cms#230]
Commit Message Templates support is currently a Beta feature from NetlifyCMS. In its current state it remains untested after the rewrite and may be potentially broken and not working at all.

- [ ] Test out feature
- [ ] Fix any issues found
- [ ] Update documentation as necessary

Docs: https://www.staticcms.org/docs/beta-features#commit-message-templates

**Comment by denyskon** [comment]
I'm using this feature from the beginning and it seems to work as expected.
