### ISSUE TITLE
UI Overhaul

### ISSUE THREAD

**Issue by Skrubbadubba** [StaticJsCMS/static-cms#282]
While browsing around I found this issue https://github.com/netlify/netlify-cms/issues/2557 from the original repo.
Austin Condiff suggested some _**awesome**_ redesigns, with some mockups and eventually a sandbox: https://codesandbox.io/s/netlify-cms-editor-design-j1cg3

It looked like some guys got together and started working on it. I'm not sure if they ever got to implementation, or why the project died. Anyways I was thinking, if you are interested, maybe you would want to contact Austin and see if this project can be restarted here.

FYI I'm a complete amateur, I wouldn't know how to contribute anything myself.

**Comment by Skrubbadubba** [comment]
Oh, sry if this should have been in discussions. I didn't notice until I had already posted.

**Comment by KaneFreeman** [comment]
I do like some of those mock ups. After the 1.0.0 release I take a look again and see what makes sense to add.
