### ISSUE TITLE
Gitea backend

### ISSUE THREAD

**Issue by denyskon** [StaticJsCMS/static-cms#310]
GitLab is the only self-hostable backend available in Static CMS. Because of its size and high resource usage, it is not a good solution for everyone. It would be great if Static CMS would support Gitea.

I already had a short look at it and would try to contribute something myself, but I need some time to understand the structure.

I started by modifying the Gitlab backend, but an issue I discovered is that Gitea doesn't seem to support PKCE flow without a client secret.

It would be great if you could provide any info where to start without using PKCE. Netlify does not support Gitea as an OAuth provider, so I don't understand how I could modify the GitHub backend for Gitea.

Resources:
- https://docs.gitea.io/en-us/oauth2-provider/
- https://gitea.com/api/swagger
- https://github.com/donskifarrell/scm-oauth-provider

**Comment by denyskon** [comment]
I now have figured out what to do and probably will open a pull request soon.

But it seems like the only way to achieve Gitea support is by using a custom OAuth provider like https://github.com/donskifarrell/scm-oauth-provider as a replacement for Netlify.
Could the backend be integrated into Static CMS if I provide a guide how to setup it? And could it be incorporated into 1.0 if I am able to provide the changes fast enough?

Btw, are there any plans for creating an own hosted OAuth provider or are you going to continue using Netlify for that?

@KaneFreeman

**Comment by KaneFreeman** [comment]
I have no plans at this time to create an OAuth provider.

Using Netlify Identity is not necessary though. Personally I use Github's OAuth directly.
