### ISSUE TITLE
Unable to preview media assets locally

### ISSUE THREAD

**Issue by SeraphRoy** [StaticJsCMS/static-cms#319]
I am trying to migrate from NetlifyCMS to StaticJsCMS. I have not deployed my changes but just trying out things locally. It seems like I am unable to preview my media assets locally.

Here's my repo that's already using NetlifyCMS https://github.com/SeraphRoy/SeraphRoy.github.io. All I changed is the admin/index.html to make it use StaticCMS.

Attached the screenshot along with developer console. Seems like it's trying to read the file from the host but since this is localhost is't just not able to read it.

<img width="1440" alt="Screen Shot 2023-01-07 at 10 31 41 PM" src="https://user-images.githubusercontent.com/13044821/211183670-b660b5fd-f69a-4607-a9d0-911073a617cd.png">

<img width="1176" alt="Screen Shot 2023-01-07 at 10 42 17 PM" src="https://user-images.githubusercontent.com/13044821/211183921-8e7e69b4-071d-4194-8e00-ad04f4d6366b.png">

I am using `https://unpkg.com/@staticcms/app@latest/dist/static-cms-app.js`

**Comment by SeraphRoy** [comment]
Weirdly enough if I use `npx netlify-cms-proxy-server` instead of `npx @staticcms/proxy-server`, preview from media tab still doesn't work (but with a different UI) but it works from the post

<img width="1274" alt="Screen Shot 2023-01-07 at 10 44 20 PM" src="https://user-images.githubusercontent.com/13044821/211184001-449a0701-abb7-4dfd-9ac5-3d22b364182c.png">

<img width="944" alt="Screen Shot 2023-01-07 at 10 44 57 PM" src="https://user-images.githubusercontent.com/13044821/211184005-54e0dd75-ab77-46db-9e00-a82ecd189255.png">

So something might be wrong with the local server?

**Comment by shawntax** [comment]
Hello! Unfortunately I'm running in to this same issue, with a NextJS 13 app using @staticcms/core: 1.2.4:

![Screenshot from 2023-01-27 15-45-28](https://user-images.githubusercontent.com/8904630/215226385-fa970b1b-9ebb-4979-8ec8-a978fe931766.png)


My config.js for local dev looks like:

```
 local_backend: true,
 editorial_workflow: false,
 cms_manual_init: true,
 backend: {
    name: 'proxy',
    proxy_url: 'http://localhost:8081/api/v1',
    branch: process?.env?.NEXT_PUBLIC_VERCEL_GIT_COMMIT_REF ?? 'main',
  },
 media_folder: 'public/media',
  ```

This same exact set-up worked for `netlify-cms-proxy-server`, so I assume it's something with https://github.com/StaticJsCMS/static-cms-proxy-server/blob/main/src/middlewares/localFs/index.ts?

**Comment by shawntax** [comment]
@KaneFreeman feel free to set this back to closed -- I updated my comment to reflect it was a config issue on my end.
