### ISSUE TITLE
cloud_name is not passed to "netlify-cms-media-library-cloudinary" module

### ISSUE THREAD

**Issue by willkuerlich** [StaticJsCMS/static-cms#331]
# cloud_name is not passed to "netlify-cms-media-library-cloudinary" module

## Bug/Issue:

When using "netlify-cms-media-library-cloudinary" with "@staticcms/core" with the bundling integration approach. It seems "cloud_name" (and possibly the "api_key") are not passed down from the init config to the netlify-cms-media-library-cloudinary module.

## Code

```
  import CMS from '@staticcms/core';
  import cloudinary from 'netlify-cms-media-library-cloudinary';

  const config = {
    media_folder: '/cms/media',
    media_library: {
      name: 'cloudinary',
      config: {
        cloud_name: 'xxx',
        api_key: 'xxx',
      },
    },
    collections: [
    ...
    ]
  }

  CMS.init({ config });
  CMS.registerMediaLibrary(cloudinary);
```

## Versions

  - @staticcms/core: 1.0.0-beta.8
  - netlify-cms-lib-util: 2.12.3
  - netlify-cms-media-library-cloudinary: 1.3.10

**Comment by KaneFreeman** [comment]
This feature (really all of the external media library options) have not been fully tested yet, so it doesn't surprise me that this is broken. I'll hopefully get around testing out it out in the next month.

**Comment by denyskon** [comment]
@KaneFreeman I think this issue can be closed as Static CNS dropped external media libraries

**Comment by KaneFreeman** [comment]
Static CMS no longer supports cloundinary.

**Comment by KaneFreeman** [comment]
Static CMS no longer supports cloudinary. If you really need it in your project, might I suggest Decap as an alternative CMS: https://decapcms.org/docs/cloudinary/
