### ISSUE TITLE
Could I filter folder collections by filenames?

### ISSUE THREAD

**Issue by razonyang** [StaticJsCMS/static-cms#349]
Thanks for your folk, I'm wondering if it is possible to filter collections by filenames (`*.zh.md`, `*.fr.md`)?

My content structure as follows, the language is a part of filename, such as `index.fr.md` - French.

```text
content
  docs
    foo/
      index.md
      index.zh.md
      index.fr.md
    bar/
      index.md
      index.zh.md
      index.fr.md
```

**Comment by Skrubbadubba** [comment]
Just based on the docs, I'm pretty sure no. Next best thing (using filenames) I think would be using `summary: {{filename}}` (https://staticjscms.netlify.app/docs/collection-overview#summary).

Easiest thing would probably be to just add a language field inside the files, and use that to filter. 

Perphaps this could be a feature request? I think overall there is some inconveniences when adding static-cms to an already exisisting project, with files and data already structured. Another useful feature to this end would be the ability to read files, and show appropriate fields in the UI based on what is being read. Better yet, the ability to create collections based on read files.

Just before posting, I found this feature: https://staticjscms.netlify.app/docs/collection-overview#view_groups. Just tried it for myself, but it didn't seem to do anything, maybe I configured it wrong.

**Comment by razonyang** [comment]
Thanks for your quick response, the use case is [Hugo's translation by filename](https://gohugo.io/content-management/multilingual/#translation-by-filename). I can re-structure my contents by storing translations in different folders, but it would be great if static CMS supports filter files by names.

**Comment by KaneFreeman** [comment]
This feature was actually a beta feature in Netlify CMS, but not yet fully supported here. I am working through the beta features to ensure they all are working and make adjustments as needed. The content i18n support is top on the list. You can track the process of it in #62
