### ISSUE TITLE
Color widget uses list/object UI element

### ISSUE THREAD

**Issue by Skrubbadubba** [StaticJsCMS/static-cms#360]
<img width="541" alt="image" src="https://user-images.githubusercontent.com/75796723/212549937-b60c32d2-0f1d-4ef5-b73d-1fd12a17dab3.png">

Not sure if this is a bug, but it doesn't look right. There is no reason for this widget to have a dropdown.

**Expected behaviour:**
It should only include the element inside the dropdown, and put the field label inside the outline, similar to the string widget.

**Comment by KaneFreeman** [comment]
Its not a bug, but a decent suggestion.
