### ISSUE TITLE
`i18n: translate` and `i18n: duplicate`

### ISSUE THREAD

**Issue by CommanderStorm** [StaticJsCMS/static-cms#380]
I would like one part of the [i18n-beta feature documentation](https://staticjscms.netlify.app/docs/beta-features#i18n-support):
`i18n: translate` and `i18n: duplicate`

Currently, these features lead to a `Config Error`, as only a bool is expected (not the strings `translate`/`duplicate`), so I would like to discuss if we should
- adapt the documentation or 
- support this alternate style

**Comment by KaneFreeman** [comment]
Yeah I suspected the `i18n` stuff didn't work 😅 . Up till now I've been focused on testing out and fixing the non-beta features. Beta features are up next, including this. Any issues you find with it feel free to report here #62
