### ISSUE TITLE
CDN url broken ?

### ISSUE THREAD

**Issue by McFlyPartages** [StaticJsCMS/static-cms#40]
I would like to try StaticCMS but the CDN addresses don't seem to work.

Maybe it's a mistake on my side? or is it normal?

PS I also tried changing the version to 1.0.0 and ^1.0.0

https://unpkg.com/@staticcms/core@^0.1.0/dist/static-cms-core.js
or
https://cdn.jsdelivr.net/npm/@staticcms/core@^0.1.0/dist/static-cms-core.js

Source : https://staticjscms.github.io/static-cms/docs/add-to-your-site/

**Comment by KaneFreeman** [comment]
c

**Comment by KaneFreeman** [comment]
The package is undergoing a complete rewrite after forking from Netlify CMS about 3 weeks ago. The first stable (v1.0.0) release (along with updated documentation) is targeted for mid to late November. I am planning to start releasing alpha builds starting this week, at which point I will turn my attention to testing out and updating documentation for the various ways the package can be used (including via CDN).

If you need a solution immediately I suggest using [NetlifyCMS](https://www.netlifycms.org/). I will be providing a migration guide from NetlifyCMS after the stable release.

**Comment by McFlyPartages** [comment]
Oooh ok sory,

I saw the 1.0.0 version on the site so I thought it was good hihi.

I'm so excited.

Thanks again for the fork which I hope will give back all the potential to this Headless
