### ISSUE TITLE
Scrolling not working

### ISSUE THREAD

**Issue by denyskon** [StaticJsCMS/static-cms#400]
When using Static CMS 1.1.0, scrolling inside an entry view doesn't work. The first screencast shows the behavior on 1.0.0, and the second one on 1.1.0.

[Bildschirmaufzeichnung vom 2023-01-21, 16-45-28.webm](https://user-images.githubusercontent.com/47871822/213874945-eb8f0a5e-1f99-4b49-bdc9-c9ece692f9de.webm)

[Bildschirmaufzeichnung vom 2023-01-21, 16-46-04.webm](https://user-images.githubusercontent.com/47871822/213874979-9d841dd3-79b3-4eb8-aaa9-aac80fec08d6.webm)

**Comment by KaneFreeman** [comment]
This is resolved in 1.1.1. It appears sync scrolling is broken at the moment so I am going to leave this issue open till I get that resolved as well.
