### ISSUE TITLE
Example of CMS.registerIcon in the doc causes error

### ISSUE THREAD

**Issue by shumiyao** [StaticJsCMS/static-cms#404]
I am afraid that [an example of CMS.registerIcon shown in the doc](https://github.com/StaticJsCMS/static-cms/blob/main/packages/docs/content/docs/custom-icons.mdx) seems to cause error. I had to make a small modification to make it work.

```
Unhandled Runtime Error
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
```

### Does not work
```
CMS.registerIcon('house', <FontAwesomeIcon icon={faHouse} size="lg" />);
```

### Works
```
    CMS.registerIcon('house',()=><FontAwesomeIcon icon={faHouse} size="lg" />);
```

Note: an arrow function of `() =>` added.

Please update the documentation. Thank you.

**Comment by KaneFreeman** [comment]
The docs have been updated. Thanks for catching that.
