### ISSUE TITLE
Dark mode support

### ISSUE THREAD

**Issue by Skrubbadubba** [StaticJsCMS/static-cms#409]
Pretty self-explanatory.

Just mentioning it, perhaps it could be added to the roadmap. I assume it wouldn't be a top priority.

It could maybe use the same color theme as the docs website.

**Comment by VitroidFPV** [comment]
I ended up doing a hacky dark mode for myself back with Netlify

![image](https://user-images.githubusercontent.com/76877124/216466100-eb0716b3-1454-4a1f-bb4e-0626d02318ea.png)
![image](https://user-images.githubusercontent.com/76877124/216466108-6304d029-bc59-49b1-b54a-52569938fe88.png)

Though it deviates a bit from the styling of the regular light theme, I'd love for a base dark theme options as well

**Comment by KaneFreeman** [comment]
Dark mode is coming in v2.0.0. Hoping to have a demo of the new UI design (with dark mode) in a couple of weeks.
