### ISSUE TITLE
docs: buggy search interactions

### ISSUE THREAD

**Issue by a-kriya** [StaticJsCMS/static-cms#410]
1. Searching and clicking on a result sometimes clears the search query and does not go to the selected page.
2. Pressing "tab" after entering a query also does the same instead of moving the focus to the results.

https://user-images.githubusercontent.com/26761352/214011088-59c39ce5-cf5e-41d5-ac5a-ede19539f763.mp4

**Comment by KaneFreeman** [comment]
This is proving to be a tricky one to nail down, as I cannot reproduce it locally. Need to dig into it further.

**Comment by a-kriya** [comment]
No prob. Thanks for looking into it anyway. A low severity issue, but I mostly filed it to give myself a first bug and to get into the codebase.

**Comment by KaneFreeman** [comment]
This should now be resolved.
