### ISSUE TITLE
Simple CMS card

### ISSUE THREAD

**Issue by denyskon** [StaticJsCMS/static-cms#421]
When sharing the GitHub repo URL, the preview card still says Simple CMS.

![Screenshot_20230124-060337~2.png](https://user-images.githubusercontent.com/47871822/214216035-c5ce8b99-0a4b-4a5e-b641-94c669ee6ec9.png)

It's not exactly a bug or so, I just noticed it and as this preview image is also often used in the GitHub app, I often get confused why it says Simple CMS.

**Comment by KaneFreeman** [comment]
This has been resolved.
