### ISSUE TITLE
An eventlistener for when the app has mounted?

### ISSUE THREAD

**Issue by Skrubbadubba** [StaticJsCMS/static-cms#443]
My use case is that I'd like to provide some custom css. I want to use custom fonts, and align my icons. 

If a stylesheet is applied at page load, it seems to not apply to the CMS. My current solution is to wait 2.5 seconds (to guarantee the react app has mounted), before applying the stylesheet.

I'm wondering if there is a way to apply as soon as the app mounts?

**Comment by KaneFreeman** [comment]
Yes, I am sure this can be added as part of #228
