### ISSUE TITLE
Registering preview component per field

### ISSUE THREAD

**Issue by Skrubbadubba** [StaticJsCMS/static-cms#460]
Here I go suggesting a feature again :P. I would like to help, but unfortunately, I know nothing about react :(. Maybe I'll have learned some next year :)

Anyways.

It would be nice if we could register a preview component per field, instead of just per collection. The reason being that we would (or maybe _could_, I don't know if it would require extra work) then get sync-scroll for the custom preview. This could be very nice for collections with lots of long fields.

**Comment by KaneFreeman** [comment]
Not sure I completely understand the request here. How would per field previews get sync scrolling? Is the sync scrolling not working right now for you, or are you looking for something about it to change?

**Comment by Skrubbadubba** [comment]
Yeah I mistook how the sync scrolling works. It does indeed work fine.

I somehow thought it worked by scrolling into view the elements whose corresponding fields are in view. Which now that I think about it doesn't make sense, as it would mean the sync-scrolling would not happen linearly. That would probably feel very weird.

I'll go ahead close this.
