### ISSUE TITLE
Azure support dropped

### ISSUE THREAD

**Issue by lpichet** [StaticJsCMS/static-cms#478]
I was not able to find any information about this, is it possible to know why you have dropped azure support ?

**Comment by KaneFreeman** [comment]
There were difficulties getting things properly setup with Azure to test the support, and ultimately in an effort to pair down the project, it was decided to drop this backend.

You can create your own version of it based off Netlify CMS's implementation, and register it manually with `registerBackend`.

However Static CMS will not be supporting Azure. We do have 4 other backends for you to choose from though: GitHub, GitLab, Bitbucket and (currently in beta) Gitea.
