### ISSUE TITLE
`media_library` property ignored for image widget

### ISSUE THREAD

**Issue by denyskon** [StaticJsCMS/static-cms#499]
According to the [docs](https://www.staticcms.org/docs/widget-image#widget-options), you can set a media_library property for an image widget, but it seems to be ignored by the media library.

Is that a bug or is the documentation simply wrong?

The value for the `default` option also doesn't look right....

**Comment by KaneFreeman** [comment]
I've fixed the `default` docs and for now I have removed the `media_library` option docs. That whole section needs further review/testing. `media_library` is mostly meant to be used with external media libraries that remain untested in Static CMS (but are on the list to be tested 😅 ).
