### ISSUE TITLE
Ordered list crashes markdown editor

### ISSUE THREAD

**Issue by denyskon** [StaticJsCMS/static-cms#508]
I have a simple markdown file with some standard frontmatter and an ordered list in body. When opening it in Static CMS, the editor changes the list numbers to 1 (like below):
```markdown
1. something
1. something else
1. a third item
...
```
When trying to modify the list or add anything, the CMS crashes with following error messages:
```
Uncaught Error: 
            Could not completely normalize the editor after 210 iterations! This is usually due to incorrect normalization logic that leaves a node in an invalid state
---
Error: Cannot get the start point in the node at path [0,1] because it has no start text node.
```

**Comment by KaneFreeman** [comment]
This seems to be related to a bug with plate and slate 0.90.0. There is an issue for it open here: https://github.com/udecode/plate/issues/2197

I've reverted our version of slate back to 0.88.1 which seems to resolve the issue. I'll keep it pinned there until plate resolves their issue.
