### ISSUE TITLE
Add sponsor button

### ISSUE THREAD

**Issue by sanch941** [StaticJsCMS/static-cms#51]
Hi everyone, can you add sponsor button? I would really appreciate to support this project.

**Comment by KaneFreeman** [comment]
I'll look into it. There a bit of setup involved in that, so it might take some time.

**Comment by KaneFreeman** [comment]
The GitHub sponsor button should hopefully be up in the next week or so, also we are now on Open Collective: https://opencollective.com/staticjscms

**Comment by KaneFreeman** [comment]
The project can now be sponsored directly through Github and the Sponsor button has been added to the top of the repo.
