### ISSUE TITLE
Request: config option to disable Local Backup (prompt)

### ISSUE THREAD

**Issue by shumiyao** [StaticJsCMS/static-cms#511]
Is there any possibility for us to have a config option to disable Local Backup?

![ScreenShot 2023-02-09 at 3 23 37 PM](https://user-images.githubusercontent.com/50849841/217856478-131b417d-bf07-40e9-8ba4-69778f29ada1.JPG)

**Comment by KaneFreeman** [comment]
Shouldn't be too hard to add and I am not opposed to it. But, if you are having specific issues with it I would be interested in hearing them to hopefully improve the functionality.

**Comment by shumiyao** [comment]
Thank you for your attention. I was wondering if the prompt could be suppressed because I am making an admin dashboard for someone new to CMS. I am afraid that she might be confused and restore local backup without understanding what it does.

**Comment by KaneFreeman** [comment]
In version `v2.0.0` (currently in beta) this dialog will no longer appear. Also there is a new confirmation option to completely disable local backups if that is desired: https://next.staticcms.org/docs/configuration-options#disable-local-backup
