### ISSUE TITLE
Netlify identity login form disapears

### ISSUE THREAD

**Issue by jkvapil6** [StaticJsCMS/static-cms#541]
When I try to log into CMS with Netlify identity widget, I have to wait around 1 second before "Manually initializing identity widget" shows in the console. If I click LOGIN WITH NETLIFY IDENTITY button before init, form will show up for a second, then disapears and the button became disabled so I can only refresh the page.

**Comment by shumiyao** [comment]
I also noticed the problem. Is this issue perhaps related?

https://github.com/decaporg/decap-cms/issues/5657

**Comment by shumiyao** [comment]
It looks like a timing issue. I made a demonstration site:

https://github.com/shumiyao/Netlify-identity-login-form-disapears-workaround/

Change logs:
https://github.com/shumiyao/Netlify-identity-login-form-disapears-workaround/commit/ebf6cf0e34937e8ae8dda530716968aa5f82a952

1. `yarn add netlify-identity-widget`
2. Remove script tag to load netlify-identity-widget in the `_document.tsx`
3. See [_app.tsx](https://github.com/shumiyao/Netlify-identity-login-form-disapears-workaround/blob/main/src/pages/_app.tsx) for details
   * Add netlify-identity-widget to window global variable when necessary
   * Hide the login button until ready

**Comment by KaneFreeman** [comment]
This issue should no longer occur as of `v2.0.0-beta.2`. The button to login will now only enable after Netlify identity is fully loaded.
