### ISSUE TITLE
Feature suggestion: CMS.registerEditorComponent()

### ISSUE THREAD

**Issue by RMunschie92** [StaticJsCMS/static-cms#555]
I've found this Netlify CMS feature incredibly valuable and unfortunately its removal is a roadblock for migrating a particular project at this time. Is there any plan to include this feature in upcoming releases?

**Comment by KaneFreeman** [comment]
The editor component feature was replaced by Shortcodes. Here is the documentation on them: https://www.staticcms.org/docs/widget-markdown#shortcodes

**Comment by RMunschie92** [comment]
Awesome, thanks @KaneFreeman!
