### ISSUE TITLE
i18n: duplicate doesn't work as expected

### ISSUE THREAD

**Issue by opohorel** [StaticJsCMS/static-cms#579]
Hi,
I'm trying to have an i18n field that has the same value in all the locales
```
{
      label: 'Certification',
      name: 'certification',
      widget: 'select',
      options: ['EN-A', 'EN-B', 'EN-C', 'EN-D', 'CCC'],
      i18n: 'duplicate',
}
```
I would expect that in my default locale I choose one of the options and that propagates to all the locales.
Instead, I have to choose the same option in each of the locales.
I pasted the config with `select` widget, but as far as I know, this also happens in the `image` widget and probably others too

**Comment by KaneFreeman** [comment]
This is resolved in v1.2.9

**Comment by opohorel** [comment]
Thank you for your fast response and for maintaining this fork :heart:

**Comment by KaneFreeman** [comment]
Scratch that. There is still a UI bug with this. Reopening.

**Comment by KaneFreeman** [comment]
NOW its fixed 😅 . 1.2.10 resolves the remaining UI bug.
