### ISSUE TITLE
Test and fully integrate i18n support into app and docs

### ISSUE THREAD

**Issue by KaneFreeman** [StaticJsCMS/static-cms#62]
i18n support is currently a Beta feature from NetlifyCMS. In its current state it remains untested after the rewrite and may be potentially broken and not work at all. After 1.0.0 release this feature will be revisited.

- [ ] Test out i18n support
- [ ] Document i18n support

**Comment by CommanderStorm** [comment]
I would like to discuss one part of the [i18n-beta feature documentation](https://staticjscms.netlify.app/docs/beta-features#i18n-support):
`i18n: translate` and `i18n: duplicate`

Currently, these features lead to a `Config Error`, as only a bool is expected (not the strings `translate`/`duplicate`), so I would like to discuss if we should
- adapt the documentation or 
- support this alternate style

(I would work on this, if you'd like)
