### ISSUE TITLE
Localisation not working?

### ISSUE THREAD

**Issue by denyskon** [StaticJsCMS/static-cms#66]
First of all, your project is really amazing and I really like the direction you're going to take with that great CMS.

When testing 1.0.0-alpha31 (over CDN) I noticed that interface localisation doesn't work.
In Netlify CMS you were able to set the "locale" parameter, but Static CMS seems to ignore it.

Was that feature dropped, or is it simply not reimplemented at the moment? It would be really nice if you kept it. I use the CMS for my school's website (https://cantorgymnasium.de) and a german translation is sometimes helpful for many of the people who edit the website 😉.

**Comment by KaneFreeman** [comment]
Yup its broken. i18n / localization support is very important and Static CMS will definitely support it. I just have not around to testing that out yet.

I have an issue open for the multiple locales support in the content (#62), which I plan to address after `1.0.0`.

I'll track this issue to fix the locales for the editor. Will prioritize this for the beta release.
