### ISSUE TITLE
Warning: You are importing createRoot from "react-dom" which is not supported. You should instead import it from "react-dom/client".

### ISSUE THREAD

**Issue by ddorstijn** [StaticJsCMS/static-cms#679]
I am using staticcms with astro + react integration. I get the following message when opening the /admin page.
```
Warning: You are importing createRoot from "react-dom" which is not supported. You should instead import it from "react-dom/client".
```
Is this an issue with StaticCMS?

**Comment by KaneFreeman** [comment]
You can safely ignore it. It is something I need to investigate at some point but does not affect your usage.

**Comment by KaneFreeman** [comment]
This warning should no longer appear as of `v2.0.0-beta.2`
