### ISSUE TITLE
Media folder per collection shows no available media even though there are images in the folder

### ISSUE THREAD

**Issue by ddorstijn** [StaticJsCMS/static-cms#684]
### Configuration (snippet)
``` typescript
export const config: Config = {
	locale: 'nl',
	logo_url: '/favicon-32x32.png',
	site_url: 'pensionalmhof.netlify.app',
	local_backend: true,
	media_folder: 'src/assets',
	public_folder: '',
	backend: {
		name: 'github',
		branch: 'v3',
		repo: 'Pension-Almhof/almhof',
	},
	i18n: {
		structure: 'multiple_folders',
		locales: locales.map(l => l.code),
		defaultLocale: 'en',
	},
	editor: {
		preview: true
	},
	collections: [
		{
			name: 'rooms',
			label: 'Kamers',
			label_singular: 'kamer',
			folder: 'src/content/rooms',
			identifier_field: 'id',
			slug: '{{title}}',
			description: 'A collection of roomtypes with their relevant information.',
			format: 'frontmatter',
			i18n: true,
			create: true,
			delete: true,
			media_folder: '../../assets/{{slug}}',
			public_folder: '../../../assets/{{slug}}',
			fields: [
				{
					name: 'id',
					label: 'Id',
					widget: 'string',
					i18n: 'duplicate',
					required: true,
				},
				{
					name: 'image',
					label: 'Image',
					widget: 'image',
					i18n: 'duplicate'
				}
			]
		}
	]
}
```

If I use the image widget to select an image the media library gives a no available images. Even though there are multiple images in the folder. Once I upload an image it does get saved in the proper destination. Only when I reopen the library again it disappears too.

![image](https://user-images.githubusercontent.com/1730282/230044937-d039babf-0069-4cf9-b5b5-6b4ebf4dabcd.png)

As a feature request it would be nice to see the media library of a collection with a button

**Comment by KaneFreeman** [comment]
The entire media library setup got some significant changes in the upcoming `v2.0.0` (currently in beta, available on npm as `v2.0.0-beta.1`).

**Comment by ddorstijn** [comment]
These changes are not yet implemented, right? Could I provide any assistance regarding the media library?

**Comment by denyskon** [comment]
@ddorstijn

You have to load the CSS styles additionally now (https://next.staticcms.org/docs/migration-guide-v2)
