### ISSUE TITLE
Markdown editor floating toolbar cut on the left edge and become unreachable [2.0 beta]

### ISSUE THREAD

**Issue by shumiyao** [StaticJsCMS/static-cms#689]
Markdown editor floating toolbar cut on the left edge and become unreachable.

Expected behavior: The left edge of floating toolbar does not go beyond the left edge of markdown editor.

![ScreenShot 2023-04-09 at 11 42 02 PM](https://user-images.githubusercontent.com/50849841/230799850-ca319264-b0bd-4c42-832f-306c8c9d3195.JPG)

----
Version: [@staticcms/core 2.0.0-beta.2](https://www.npmjs.com/package/@staticcms/core/v/2.0.0-beta.2)

**Comment by KaneFreeman** [comment]
This is resolved in beta.3
