### ISSUE TITLE
[suggestion] use field labels for summary fields

### ISSUE THREAD

**Issue by denyskon** [StaticJsCMS/static-cms#698]
Currently, when setting summary fields for the table view, their capitalized versions are used for the table header. But at least for me, the internal field name and the label don't always match up in a way that doesn't confuse other authors. It would be nice if the table header could use the label string set in the field configuration.

**Comment by denyskon** [comment]
@KaneFreeman isn't that fixed with beta 5?

**Comment by KaneFreeman** [comment]
Yup. I meant to close this. 😄
