### ISSUE TITLE
Demo Deployment missing CSS and console errors

### ISSUE THREAD

**Issue by pReya** [StaticJsCMS/static-cms#705]
Currently, the Demo Deployment under https://demo.staticcms.org/ has some problems:

- The fonts are not correct (Seems like a CSS file is missing)
- There is an error about an undefined object in the JS console, right on the main landing page

**Comment by KaneFreeman** [comment]
These issues can be ignored. The upcoming `v2.0.0` (currently in beta), resolves both of these issues.

**Comment by KaneFreeman** [comment]
https://next.demo.staticcms.org/

**Comment by pReya** [comment]
Thanks for the new link. I just wanted to make sure, you're aware of it. For potential new users, having a bug-ridden Demo link on the website/readme may lead to a bad impression. Any idea when v2 will be released?

**Comment by KaneFreeman** [comment]
The target is by the end of the month.
