### ISSUE TITLE
Is it possible to set the cms "publish" button to create a PR instead of try to merge things directly in on Github?

### ISSUE THREAD

**Issue by liufuyang** [StaticJsCMS/static-cms#756]
Hey there, thanks for creating this nice tool.

One question about the Publish button/feature:

Can we make it in a way that only a PR is made (then another button to merge or require manual merge is also fine).

One thing is blocking us from trying this tool out now is that on our Github repos we have main branch protection that only allows PR merges.

It would be nice if we have similar features as mentioned in the decapcms(the previous netlify-cms) https://decapcms.org/docs/configuration-options/#publish-mode.

We don't need fancy UIs yet to view the "in review" changes, but if the single "Publish" button can be configured to do a PR creation then it would be pretty nice :)

**Comment by KaneFreeman** [comment]
At this time we are not planning on supporting pull requests or an editorial workflow. This kind of feature is extremely reliant on the backend used (even Decap only supports it with the Github backend), and we have decided to focus on features that all backends can use.

**Comment by liufuyang** [comment]
I see, thank you very much. Just to mention that this will be a deal breaker for us but thank you for the good work here, perhaps later something will come :)
