### ISSUE TITLE
DateTime widget broken?

### ISSUE THREAD

**Issue by denyskon** [StaticJsCMS/static-cms#77]
The DateTime widget seems to be broken.
It doesn't render the time from existing posts, and when trying to set new date, I get the following message:
`Starting with v2.0.0-beta.1 date-fns doesn't accept strings as date arguments. Please use `parseISO` to parse strings. See: https://github.com/date-fns/date-fns/blob/master/docs/upgradeGuide.md#string-arguments`

**Comment by KaneFreeman** [comment]
I'm addressing the date picker issue. However for the not loading existing dates, that could be a formatting issue. Netlify CMS used moment for its date processing and Static CMS switched to using date-fns. There are some difference in the format strings between the two, most notably:

- `YYYY` should now be `yyyy`
- 'DD` should now be `dd`

Just double check that your `format` field in your `config.yml` matches the data's format. When no format is specified, the format defaults to ISO (`yyyy-MM-dd'T'HH:mm:ss.SSSXXX`).
