### ISSUE TITLE
Trying to add a link in the editor opens the media selector instead

### ISSUE THREAD

**Issue by henare** [StaticJsCMS/static-cms#774]
Firstly, thank you for making Static CMS — it's really amazing :heart_eyes: 

When trying to create a link in the post editor using either the "File / Link" option or the link icon in the hovering tools, the media selector is opened instead of the link editing dialogue. This is reproducible [on the demo site](https://demo.staticcms.org/#/collections/posts/new):

![image](https://user-images.githubusercontent.com/48945/235647128-6d4bd23b-7340-4808-9c11-30e58d55c0c5.png)

Media selector is opened and I can't create a link:

![image](https://user-images.githubusercontent.com/48945/235647250-d9079e82-5e98-407e-af95-5e865f7e1ad4.png)

**Comment by KaneFreeman** [comment]
It should open the media library, but by default it should also allow you to enter a URL in the media library. That is not happening. It should be fixed in the next release.

**Comment by henare** [comment]
Spectacular, thank you so much for the lightning-fast fix :sparkles: Looking forward to the release :popcorn:
