### ISSUE TITLE
Setting custom project logo does not work

### ISSUE THREAD

**Issue by Nuc1eoN** [StaticJsCMS/static-cms#787]
I have followed https://www.staticcms.org/docs/configuration-options#custom-logo to set a custom project logo.

My config looks like this:
```js
CMS.init({
  config: {
    ...
    logo_url: "/favicon.svg",
    ...
});
```
`favicon.svg` resides under the `public` folder of my astro project.

According to the inspector's network tab the file _is_ being loaded: `Status Code: 200`

But the admin interface still bears the default logo:
![image](https://github.com/StaticJsCMS/static-cms/assets/2538022/3154fa18-d491-4e0a-9364-c4ef4ceb32b3)

**Comment by KaneFreeman** [comment]
This has been fixed and will be in the next release (hopefully by the end of the week).
