### ISSUE TITLE
[Feature] Make editor/preview pane resizable horizontally

### ISSUE THREAD

**Issue by Nuc1eoN** [StaticJsCMS/static-cms#797]
I'd appreciate the possibility to resize the editor with the mouse, just like in netlify cms:

![image](https://github.com/StaticJsCMS/static-cms/assets/2538022/c28855f9-41d2-40f3-8f7c-2e2279a68fa3)

I think it would greatly enhance the user experience for everybody.

**Comment by McFlyPartages** [comment]
I am also interested because the edition bar is very small.

**Comment by KaneFreeman** [comment]
This is being targeted for the `v4.0.0` release.

**Comment by mnordhaus** [comment]
From my point of view it would be nice if it is possible to hide the editor entirely to provide a better preview.

The following issue is related here: https://github.com/StaticJsCMS/static-cms/issues/768
