### ISSUE TITLE
URL and Alt fields styling bug inside image modal window

### ISSUE THREAD

**Issue by timotheegoguely** [StaticJsCMS/static-cms#809]
When we add an image to a markdown field, the URL and Alt fields from the opening modal are displayed over the top left icon. You can easily reproduce this bug in the official demo.

![image](https://github.com/StaticJsCMS/static-cms/assets/8271134/ec954235-d96b-49a1-af62-f36ef29630bb)

**Comment by KaneFreeman** [comment]
There were changes to that modal recently. As of current I am not able to reproduce this in the latest version. Can you update to 2.3.3 and confirm if this issue is still present or not?

**Comment by timotheegoguely** [comment]
It looks fine on Chromium based browsers, but it is still present is the online demo in Firefox (113.0.1): https://demo.staticcms.org/#/collections/posts/entries/2015-02-15-this-is-a-json-frontmatter-post

And it even worse on Safari (15.6.1) as you can see in the screenshot bellow:
![image](https://github.com/StaticJsCMS/static-cms/assets/8271134/fa09e896-cf58-40ca-801c-e8586a7f86f2)

Adding `w-full` class on the SVG element should fix it.
