### ISSUE TITLE
MDX Editor

### ISSUE THREAD

**Issue by KaneFreeman** [StaticJsCMS/static-cms#81]
### What
Build a new markdown editor using [Plate](https://plate.udecode.io/) that supports mdx and html files.

### Why
During the initial migration to TypeScript the biggest problem spot was the Markdown editor. Its dependencies were decently out of date, and the versions being used had no TypeScript support at all. Upgrading it as it was going to be extremely difficult due to my lack of understanding behind the current setup and the fact that all of the dependencies had undergone significant breaking changes themselves. As such I opted (in #35) to switch the editor to a pre-built markdown editor (Toast UI). This provided the TypeScript support that was needed and overall was a very nice editor to use. The issues with it started showing though when trying to customize it, especially when integrated images from it into the media library. The documentation for the editor is not very good around customizations and the API that should support it does not behave as one would expect. I fear extending the editor any further for things like short codes or mdx would be near impossible in its current state.

So this brings us full circle. Netlify CMS's editor was built with (a now old version of) Slate, a very extensible open source editor. The issues with it were how out of date it had gotten and not what it was using. I took the shortest route to a workable product at the time and now it is time to circle back and do this the right way.

### Timeline
- [x] 1.0.0 - New editor with markdown support
- [ ] Post 1.0.0
   - [ ] MDX support in the editor
   - [ ] Raw markdown editor

**Comment by KaneFreeman** [comment]
The initial version coming in `1.0.0` will NOT support MDX, but it will support markdown and some extended styling behaviors (font color, back color, alignment, etc). MDX support will be added post `1.0.0` release.

**Comment by KaneFreeman** [comment]
Markdown only editor with shortcode support is now available in `1.0.0-beta.3`

**Comment by KaneFreeman** [comment]
It has been decided not to presue MDX support for the editor at this time. Instead focus will be put on improving the markdown editor.

**Comment by timotheegoguely** [comment]
Could you detail what markdown editor improvements are planned, in addition to the recent toolbar customization? 
Good job on this point by the way :)

**Comment by KaneFreeman** [comment]
The only real definite plan atm is adding the missing markdown mode. Beyond that I will mostly focus on bug fixes. If you have any specific suggestions for changes you would like to see feel free to suggest them.

**Comment by timotheegoguely** [comment]
When you say "markdown mode", do you mean a markdown raw editor mode? It would indeed be very useful to have it.

**Comment by KaneFreeman** [comment]
Yes a raw Markdown editor

**Comment by timotheegoguely** [comment]
Hi, any updates about the raw Markdown editor mode?
I'm really looking forward to using it :)
