### ISSUE TITLE
Css prop name typo in PostPreviewCard

### ISSUE THREAD

**Issue by shumiyao** [StaticJsCMS/static-cms#812]
I am afraid that `backgroundRepat` might be a typo of `backgroundRepeat`.

Thank you for your attention in advance.

https://github.com/StaticJsCMS/static-cms/blame/c74b07a125291ee44a92772608a8cf2ba7c85653/packages/demo/src/cms.jsx#L41

**Comment by KaneFreeman** [comment]
Thanks for catching that. Its been fixed.
