### ISSUE TITLE
Wrong new folder path in draft article

### ISSUE THREAD

**Issue by denyskon** [StaticJsCMS/static-cms#824]
When creating a new folder from a draft entry (with media_folder static/media), the resulting path for the created folder becomes static/static/media/new_folder for some reason. It seems to only happen when creating a new folder from new entry which wasn't published yet, the other cases (published entry, media tab) work fine.

I didn't have enough time to look in to this issue so far, just wanted you to know that it exists.

**Comment by KaneFreeman** [comment]
The media path management system is an utter mess. I've got a fix for this for now. At some point in the future I believe a complete rewrite of how assets and asset paths are handled is in order.

**Comment by KaneFreeman** [comment]
The fix for this is going out in `v2.5.0`. Targeting today or tomorrow for its release.

**Comment by denyskon** [comment]
> The media path management system is an utter mess. I've got a fix for this for now. At some point in the future I believe a complete rewrite of how assets and asset paths are handled is in order.

I also noticed that when implementing folder support. Thank you for your help, I didn't manage to find the source of the problem in that mess.
