### ISSUE TITLE
Previews not working ( Body, title, date)

### ISSUE THREAD

**Issue by pxrpl** [StaticJsCMS/static-cms#829]
I’ve replaced Decap CMS for StaticCMS, I’ve done everything in the migration guide, and when I try to see the previews it doesn’t work.

as you can see in this image the body, the date don’t appear in the preview, and the preview url box, I don’t want it to appear on the preview. Here’s the link to my repo: [pxrpl/blog](https://github.com/pxrpl/blog) Overall this fork is amazing but I can’t figure out how to set it up.

![5BD76106-6B88-4682-A12D-77DAFD3189E8](https://github.com/StaticJsCMS/static-cms/assets/87479344/c09c1d5e-6482-40b1-b4ab-0d0a94ff6fc5)

**Comment by denyskon** [comment]
You can create your own previews and customize them the way you want, see https://www.staticcms.org/docs/custom-previews#editor-preview

**Comment by pxrpl** [comment]
Thanks! Do you have any examples I can check out to understand it more?

**Comment by denyskon** [comment]
You can check out mine at https://git.cantorgymnasium.de/gcg/gcg-website/src/branch/master/static/admin/previews/page-previews if you want. They're a bit chaotic, but at least you may understand the structure.

**Comment by pxrpl** [comment]
What files? Sorry, I am not able to find the file of the preview

**Comment by denyskon** [comment]
Ech of them are previews 😝 (I have a lot of different collections.....) I think https://git.cantorgymnasium.de/gcg/gcg-website/src/branch/master/static/admin/previews/page-previews/blog-preview.js is the most complete one, but please pay attention that I've moved some parts out to separate files (the import statements in the beginning)

**Comment by pxrpl** [comment]
Ohh hahaha thanks

**Comment by pxrpl** [comment]
Can you make a script with just shows the title, the date and the body? And uses this css: css/main.css and css/syntax.css, also the date still does not work, I can’t set the date

**Comment by KaneFreeman** [comment]
The `date` widget no longer exists. It's `datetime`. The `date` widget is a deprecated feature in DecapCMS and was removed here

**Comment by pxrpl** [comment]
Yes but I just want to display the date and not the time

**Comment by KaneFreeman** [comment]
`datetime` can do just date, just time or date and time.

Here is the example for just date: https://www.staticcms.org/docs/widget-datetime#date-picker

**Comment by KaneFreeman** [comment]
For the post URL, @denyskon is right. The only way to hide that is to create a custom preview.

As for the body, its not showing because of your HTML you have for your image. The `markdown` widget uses MDX to render its preview. MDX can handle HTML, but it very picky about all tags (in your case `<img>`) have a closing tag. Otherwise it will kind of silently error out.

So can your image tag to have a `/` at the end.

```html
<img src="/images/uploads/2023/11ty.png " alt="Origins" height="150px" style="float: right; margin-left: 10px;" />
```
