### ISSUE TITLE
Image caption field in Media Library

### ISSUE THREAD

**Issue by colmoneill** [StaticJsCMS/static-cms#830]
Thanks for all the great work on Static CMS, very much enjoying using it!

Wondering if there is a plan to have a caption field along with individual media objects in the Media Library. Since it is possible to select multiple pictures with the image widget, I'm looking to build a gallery/lightbox section on a website but need the ability to show individual image captions, as well as needing it as an `alt=` attribute for accessibility purposes.

If there is a better approach to this, I'd be keen to try it.

Thanks again and all the best.

**Comment by denyskon** [comment]
Wouldn't it be easier to make a list, with each Item containing an image field, a caption field and an alt text field?

**Comment by anthonykasabian** [comment]
I think it's a good way, that's how I solved it in several projects. To put the caption in the meta of the image. In hugo you can read those tags with $image.Exif.tags.description

I think it's a matter of organizing things in common. But in a convenient way we're getting images from the authors wich manage them on their systems with tools like bridge or lightroom. Maybe that's a roundtrip for you.
