### ISSUE TITLE
Markdown files with <style> definitions do not get rendered in preview

### ISSUE THREAD

**Issue by Nuc1eoN** [StaticJsCMS/static-cms#832]
In my astro project, I have instances where I have `<style></style>` in my markdown files (at the very bottom of the file).

Those markdown files fail to render in StaticCMS' preview.

Solely `<style></style>` will not break the preview, but as soon as there is a definition, for instance:
```html
<style>
   .foo {
      margin-top: 1rem;
   }
</style>
```

The rendering preview to the right will be empty.

My suggested workaround/fix for this would be to ignore anything that is `<style>...</style>`.
Another, albeit more involved option might be to actually apply the style definitions to the preview.

However you probably know best how to tackle this. Thank you in advance.

**Comment by KaneFreeman** [comment]
The markdown editor only supports markdown. It does support html `style` tags. If you want an HTML editor, you can look into making an HTML widget out of something like TinyMCE.

**Comment by Nuc1eoN** [comment]
I think you might have mis-understood my bugreport. The markdown editor works as expected, however the preview fails to render.
I cannot remove the <style></style> definitions because that would "break" the site.

My suggestion was therefore, that the rendering preview should ignore anything that is within `<style></style>` tags.

**Comment by Nuc1eoN** [comment]
To be clear, I do not expect that <style></style> should be rendered in the preview. However I do expect that it will not break the preview, currently the preview is just *blank* if there exist any <style></style> definition.
See:
![image](https://github.com/StaticJsCMS/static-cms/assets/2538022/8a4592c0-86b9-44c9-a171-1dce133bed00)
