### ISSUE TITLE
[v3beta1] Problem when try to select start of line

### ISSUE THREAD

**Issue by McFlyPartages** [StaticJsCMS/static-cms#837]
Hy,

I'm using Static CMS v3 beta 1 and I think I've found a bug in Firefox and Brave.

>The problem is not present in v2

When we try to click at the beginning of a line in any field, the cursor won't go there. You have to click on the second or third character and come to the first position with the arrows.

Here's the picture.
![static_bug_selection_start_line](https://github.com/StaticJsCMS/static-cms/assets/44530252/33000e41-adb8-4ea2-aa58-ea8557765ced)

**Comment by McFlyPartages** [comment]
For information, the probleme is not only on mobile

**Comment by KaneFreeman** [comment]
This is resolved in beta 2
