### ISSUE TITLE
Clicking on the map widget duplicates it

### ISSUE THREAD

**Issue by Cynosure-North** [StaticJsCMS/static-cms#841]
[Screencast from 2023-06-14 17-50-08.webm](https://github.com/StaticJsCMS/static-cms/assets/52474045/cc105ebc-a7d8-45da-ab7c-987342ff4611)
![image](https://github.com/StaticJsCMS/static-cms/assets/52474045/4d7a8605-9a5c-48b4-aea8-ea43ffdab18f)

I've tested on Chromium 114.0.5735.106 & Firefox 113.0 on Ubuntu 22.10
It also happens if the type is set to LineString or Polygon, but then it only occurs when line or polygon ends.

**Comment by KaneFreeman** [comment]
This is resolved in `v2.5.1`
