### ISSUE TITLE
Not possible to create list widget with empty default

### ISSUE THREAD

**Issue by drewbo** [StaticJsCMS/static-cms#843]
A recent update (https://github.com/StaticJsCMS/static-cms/pull/704) made it so that list widgets are required to have at [least one item for the default](https://github.com/StaticJsCMS/static-cms/blob/main/packages/core/src/widgets/list/schema.ts#L11). It seems like many times users would want to configure the default to be an empty list. Please let me know if this is intended behavior and I'm misunderstanding the schema or if this warrants a small PR. Thanks

**Comment by KaneFreeman** [comment]
Not setting a default is the same as an empty list.
