### ISSUE TITLE
Add link using modal in Markdown Editor

### ISSUE THREAD

**Issue by timotheegoguely** [StaticJsCMS/static-cms#844]
When we try to add a link on a text using the modal window, there is several issues:
- when multiple words are selected, the Text field is wrong: for example, `static sites generators` is converted to `st`
- when we close the window after adding some link in the URL field, the link isn't replacing the selected text as expected

I recorded a short video on the [demo](https://demo.staticcms.org/#/collections/posts/entries/2023-06-29-post-number-1) to help you understand and reproduce the bug (I'm using Firefox):

https://github.com/StaticJsCMS/static-cms/assets/8271134/1d8dad3c-13a2-4a5f-9055-55430510cee2

**Comment by KaneFreeman** [comment]
This is resolved in version `3.1.1`
