### ISSUE TITLE
Request: add back support for TOML front matter

### ISSUE THREAD

**Issue by onodera-punpun** [StaticJsCMS/static-cms#86]
This was present in netlifyCMS but it seems it got stripped? Could this possible be added back in?

**Comment by KaneFreeman** [comment]
Yes, its on my list to re-add. It was removed due to some issues with the dependencies that were used. When I get to it, I will be reimplementing it with https://www.npmjs.com/package/@ltd/j-toml

**Comment by KaneFreeman** [comment]
Version `1.0.0-beta2` now available on npm restores TOML support.
