### ISSUE TITLE
Option to disable mobile view

### ISSUE THREAD

**Issue by Pension-Almhof** [StaticJsCMS/static-cms#862]
Hello,

I just updated to version 3.1.2 and I noticed the whole layout of the website has changed. It looks nice on mobile, and I think this change is made as part of the 3.0.0 update. But since I am not planning on editing with my phone I would like my old UI back. Where I have a better overview and can edit two locales at once. Is this currently possible?

**Comment by KaneFreeman** [comment]
No there is no way to disable mobile layout. The mobile layout only appears if your screen is less than 768px wide. The desktop version is unchanged.
