### ISSUE TITLE
Add id and/or class to UI sections and components

### ISSUE THREAD

**Issue by timotheegoguely** [StaticJsCMS/static-cms#867]
Adding `id` to UI sections and `class` to components would allow to write custom CSS more easily.

For exemple: for **widgets**, we should have some classes mirroring widgets names like `widget`, `widget-date`, `widget-boolean`, `widget-markdown`, `markdown-toolbar`, etc. Right now, there is only `data-testid="field"` `data-testid="field-wrapper"` data attributes, which are the same for all fields and looks like some debug stuff not to be trusted.

There is already some `id` like `main-view`, `control-pane`, so I simply think this should be applied to more parts of the UI.

**Comment by KaneFreeman** [comment]
Likely it will be classes, as that gives a lot more flexibility. Right now I am thinking something like this example of a text widget:

```html
<div data-testid="field" class="CMS_Field_root CMS_WidgetText_root CMS_Field_cursor-text CMS_Field_error">
  <div data-testid="field-wrapper" class="CMS_Field_wrapper">
    <label data-testid="label" class="CMS_Label_root CMS_Label_cursor-text CMS_Label_error">
      Required With Default
    </label>
    <div
      data-testid="textarea-input"
      class="MuiInput-root MuiInput-multiline CMS_TextArea_root CMS_WidgetText_input-wrapper"
    >
      <textarea
        class="MuiInput-input MuiInput-multiline CMS_TextArea_input CMS_WidgetText_input"
        style="height: 80px; padding-bottom: 12px"
      ></textarea>
    </div>
    <div data-testid="error" class="CMS_ErrorMessage_root">Required With Default is required.</div>
  </div>
</div>
```

**Comment by KaneFreeman** [comment]
This is done in version `3.3.0`.
