### ISSUE TITLE
Broken hooks rule with registerPreviewTemplate and MDXProvider

### ISSUE THREAD

**Issue by creativiii** [StaticJsCMS/static-cms#87]
I'm currently transferring my site from `netlify-cms` and I'm encountering issue with my previous setup for rendering custom markdown.

Previously my working code looked like this:
```
CMS.registerPreviewTemplate('blog', HOCPreview)

// ...

const HOCPreview = (props: TemplatePreviewProps) => {
    return (
        <ArticleProvider>
            <Preview {...props} /> 
        </ArticleProvider>
    )
}
```

In the above, `Preview` is a component that takes some data and displays it:
```
const Preview = (props: TemplatePreviewProps) => {
    const entry = props.entry
    const body = (entry.data as { body: string }).body

    return <>{body}</>
}
```

And `ArticleProvider` is a more complex context which adds my MDX components:
``` 
const ArticleProvider = ({ children }: { children: React.ReactNode }) => {
    return <MDXProvider components={components}>{children}</MDXProvider>
}
```

The idea here is to pass the Markdown through the same MDXProvider I use for my frontend and render it as it would on my site.

This worked perfectly previously, but I'm now getting:
```
static-cms-core.js?600c:304 Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
    at Object.throwInvalidHookError (react-dom.development.js?61bb:14906:1)
    at Object.useContext (react.development.js?72d0:1504:1)
    at useMDXComponents (index.js?8019:67:29)
    at MDXProvider (index.js?8019:89:1)
    at Sa (static-cms-core.js?600c:81:1612500)
    at kl (static-cms-core.js?600c:81:1669564)
    at bc (static-cms-core.js?600c:81:1658550)
    at vc (static-cms-core.js?600c:81:1658483)
    at gc (static-cms-core.js?600c:81:1658347)
    at ic (static-cms-core.js?600c:81:1653442)
    at x (static-cms-core.js?600c:81:1722869)
    at MessagePort.O (static-cms-core.js?600c:81:1723405)
```

The issue is definitely happening within `MDXProvider`, but all of it is definitely valid React code. 
Is there anything obvious that jumps out here? Working on creating a reproduction at the moment.

**Comment by KaneFreeman** [comment]
I have a hunch, as part of the modernization effort the project has been updating to use React 18.2.0 (NetlifyCMS uses React 17). Currently it is **not** set as peer dependency (this will change before the stable release). So if you are on a version of React below 18.2.0 then both versions of react would be included in the final build. I suggest matching your React version to StaticCMS's for now IF you are bundling.

**Comment by KaneFreeman** [comment]
Closing this issue as stale. If you are still having this issue please feel free to comment here and I'll reopen it.

**Comment by michaelbaudino** [comment]
For people finding this issue: I had the exact same problem while migrating from NetlifyCMS, even when matching React and ReactDOM versions (_i.e._ using `18.2.0` explicitely).

I solved the issue by replacing all `React.createElement` by `h` and all `React.useState` by `useState` (not namespaced), as mentioned in [the custom preview documentation](https://staticjscms.netlify.app/docs/custom-previews#react-components-inline).
