### ISSUE TITLE
Local backups won't be disabled if already present

### ISSUE THREAD

**Issue by enricogallesio** [StaticJsCMS/static-cms#871]
Hello!
First, let me thank you for this amazing project!

Is it just me or 
`disable_local_backup: true,`
won't remove the local backups for entries which already have one?

I have a client who is doing a lot of confusion with local backups. I have tried disabling local backups both on a collection bases and a general bases but the "Has local backup" continues to be shown, so I guess those are not ignored like I would expect.

Anyone can confirm? Is this the intended behavior?

Alternatively, is there any way to easily flush all local backups?

thank you very much in advance!

**Comment by KaneFreeman** [comment]
This is fixed in version `3.3.0`.

**Comment by enricogallesio** [comment]
Thanks!!!
