### ISSUE TITLE
Response for config.yml was not yaml. (Content-Type: text/plain; charset=utf-8)

### ISSUE THREAD

**Issue by onodera-punpun** [StaticJsCMS/static-cms#89]
I get this warning in safari, I don't know if I'm doing something wrong, if this is harmless, or what.

**Comment by KaneFreeman** [comment]
If your CMS is still loading properly than you can ignore this. Its a warning that your server is not returning the correct content type for the file. But since `yaml` is read in as plain text anyways it should not matter.
