### ISSUE TITLE
Broken multiline quotes

### ISSUE THREAD

**Issue by denyskon** [StaticJsCMS/static-cms#892]
[Bildschirmaufzeichnung vom 2023-09-21, 20-46-04.webm](https://github.com/StaticJsCMS/static-cms/assets/47871822/a74779b8-5436-4f48-ae00-2d8ee738b546)

As seen in the video, I have a post with a multiline quote. The raw markdown looks like this:
```markdown
> One line  
> Another line  
```
(two spaces after each line = newline)
This can also be achieved inside the markdown editor.
But when opening the published post again, all the quote lines are being smashed into one looooong line.

**Comment by KaneFreeman** [comment]
What version are you using?

**Comment by denyskon** [comment]
My version is set to `^3.0.0`, so it should be the latest one - 3.3.1

**Comment by KaneFreeman** [comment]
Where does the double space new line come from? It doesn't seem to be standard. For example it does not work on Github.

It seems to be more standard to do an empty line with `>`.

```md
> One line
>
> Another line
```

**Comment by denyskon** [comment]
Double space is defined in the commonmark spec as an equivalent of <br/>

But even if I use your suggested method, the issue still happens if I try to edit a published post.

**Comment by KaneFreeman** [comment]
This should be fixed in `v3.3.3`.
