### ISSUE TITLE
Extend filter option for folder collections

### ISSUE THREAD

**Issue by CamilleScholtz** [StaticJsCMS/static-cms#90]
Currently my directory structure looks as follows:

```
posts
  - _index.md
  - some-post-name
    - index.md
    - image.png
  - some-other-post-name
     - index.md
     - image.jpg
```

I only want to list the the nested `index.md` files in the collections, but as it also `_index.md` gets included. Is there a way to fix this?

**Comment by KaneFreeman** [comment]
I will have to look into this when I get around to evaluating the nested folders feature. It was a beta feature for NetlifyCMS and I have not yet tested it or validated it in any way after the move/rewrite. Likely I will get to this after the 1.0.0 stable release.

If you want to take a look/poke at it yourself go for it!

**Comment by KaneFreeman** [comment]
`v2.4` will include significantly expanded filtering capabilities for folder collections. Documentation to come shortly.
