### ISSUE TITLE
Datetime keyboard input not possible

### ISSUE THREAD

**Issue by denyskon** [StaticJsCMS/static-cms#901]
If trying to edit a datetime field by typing in a value, the cursor jumps to the end of the field, and it isn't possible to input anything. As a consequence, it also isn't possible to empty a datetime field.

**Comment by KaneFreeman** [comment]
Yeah, currently the datetime widget uses the mobile versions of the input. Which is why keyboard input doesn't work.

I am going to update the library in `v4.0.0` and will switch it to use the regular version (which seems to responsively switch between desktop and mobile). That should resolve this.
