### ISSUE TITLE
UI issues in relation widget

### ISSUE THREAD

**Issue by denyskon** [StaticJsCMS/static-cms#905]
I noticed a few UI issues in the relation widget.

1. In Firefox, there's a weird focus ring, which isn't there in Chrome. It seems like it is caused by a Firefox-specific Tailwind code block. I would've submitted a PR, but unfortunately I have no idea how to get rid of it correctly with the new CSS structure introduced in the latest release.
![grafik](https://github.com/StaticJsCMS/static-cms/assets/47871822/2f39d9f4-fc85-4e06-b8e0-55b76644a860) 
![grafik](https://github.com/StaticJsCMS/static-cms/assets/47871822/4bb92c6a-2f19-4d7b-873e-857d45675883)
It also appears in the text widget:
![grafik](https://github.com/StaticJsCMS/static-cms/assets/47871822/224da62b-a9bb-4e55-85f7-1a917b7b479d)

3. The loading icon overlaps with the arrow icon
![grafik](https://github.com/StaticJsCMS/static-cms/assets/47871822/cc5c353e-8031-4e4b-bf0e-78dead5b9ad6)

4. The autocomplete list for the relation is overlaid by the Markdown editor toolbar

![grafik](https://github.com/StaticJsCMS/static-cms/assets/47871822/778016e7-134c-48d6-9694-b36c9c0211df)

I'm using the latest version :)

**Comment by KaneFreeman** [comment]
#3 is already fixed in the `next` branch, so that fix will be in the beta coming soon.

**Comment by KaneFreeman** [comment]
This is fixed in `v3.3.4`
