### ISSUE TITLE
i18n multiple folders doesn't append the language on the end of the folder property but inserts it after the first folder

### ISSUE THREAD

**Issue by Pension-Almhof** [StaticJsCMS/static-cms#941]
## Config
```typescript
import type { Config } from "@staticcms/core";
import { locales } from '@translations/locales.json';

export const config: Config = {
	locale: 'nl',
	logo_url: '/favicon-32x32.png',
	local_backend: false,
	media_folder: 'src/assets',
	public_folder: 'src/assets',
	backend: {
		name: 'github',
		branch: 'main',
	},
	media_library: {
    max_file_size: 4000000,
    folder_support: true
  },
	i18n: {
		structure: 'multiple_folders',
		locales: locales.map(l => l.code),
		defaultLocale: 'en',
	},
	editor: {
		preview: true
	},
	collections: [
		{
			name: 'homepage_highlights',
			label: 'Hoofdpagina/highlights',
			label_singular: 'highlight',
			description: 'Dit zijn de icoontjes die je kunt zien onder het kopje "Wij bieden"',
			identifier_field: 'id',
			slug: '{{title}}',
			create: true,
			delete: true,
			i18n: true,
			format: 'frontmatter',
			folder: 'src/content/homepage_highlights',
			fields: [
				{
					name: 'id',
					label: 'id',
					i18n: 'duplicate',
					widget: 'number',
					hint: 'Dit bepaald de volgorde van de highlights'
				},
				{
					name: 'name',
					label: 'Naam',
					i18n: true,
					widget: "string"
				},
				{
					name: 'image',
					label: 'Background image',
					i18n: 'duplicate',
					widget: 'image'
				},
			]
		},
};
```

## Issue
Creating a new highlight results in a new file in `src/[lang]/content/homepage_highlights/[slug].md` instead of `src/content/homepage_highlights/[lang]/[slug].md`.

This seems to be different from what is [documented](https://www.staticcms.org/docs/i18n-support#top-level-configuration). This says: multiple_folders - persists files in `<folder>/<locale>/<slug>.<extension>`

**Comment by KaneFreeman** [comment]
I am having some trouble reproducing this issue. Can you provide a repository where this is occurring please.

**Comment by Pension-Almhof** [comment]
Alright, I created a test site. The github repository can be found [here](https://github.com/Pension-Almhof/StaticCMS-bugtest/).
The website it builds can be found here: https://main--harmonious-kringle-af183b.netlify.app/en/

As you can see from the latest commit it creates the extra files in src/[locale]/content/...

**Comment by KaneFreeman** [comment]
Okay I think I have narrowed it down. It likely caused by your slug being invalid. You have your slug set to the `title` field, which does not exist in your collection. This is messing up the CMS when it tries to insert the locale into the path. Switch your slug to a field that exists.

**Comment by Pension-Almhof** [comment]
You are right. Setting the slug to a proper field and using the latest version seems to have resolved the issue. Many thanks for the help.
