### ISSUE TITLE
Light mode button backgrounds are sometimes transparent, Causing it to be almost impossible to read

### ISSUE THREAD

**Issue by Pension-Almhof** [StaticJsCMS/static-cms#942]
In darkmode you get a nice blue background. The button does get a background in light mode when you hover over it. I've seen it with logging in and the use selected button in the media library and the publish button during editing.

### Publish
![image](https://github.com/StaticJsCMS/static-cms/assets/118728236/609d4e50-9063-47a7-a397-32f5dae94b99)

### Media library
![image](https://github.com/StaticJsCMS/static-cms/assets/118728236/492ec2c8-bc41-411e-95f1-62241b5f2601)
When hovered:
![image](https://github.com/StaticJsCMS/static-cms/assets/118728236/c97d53da-1ed0-4133-81fa-5b9c7d156d4b)

### Login
![image](https://github.com/StaticJsCMS/static-cms/assets/118728236/80b4500c-8c54-4689-b925-b2fc62173589)
When hovered:
![image](https://github.com/StaticJsCMS/static-cms/assets/118728236/2b510c2d-edf9-4dd3-b644-ca7ce53cef65)

**Comment by KaneFreeman** [comment]
What browser are you using?

**Comment by Pension-Almhof** [comment]
Problems are tested on:

Microsoft Edge
Version 118.0.2088.61 (Official build) (64-bit)

Firefox
Version 119.0 (64-bits)

**Comment by Pension-Almhof** [comment]
It seems to be hapening because of the reset of tailwindcss I am using after further inspection.

![image](https://github.com/StaticJsCMS/static-cms/assets/118728236/6d01df33-9e5d-40d4-a00c-98fcde9c1422)

Although I wouldn't know how to fix this. It seems the css of the light mode has a lesser importance than the reset.

**Comment by KaneFreeman** [comment]
There are two options to try:

1. If possible do not include your tailwind setup on the admin page. Static CMS already uses tailwind, so if you need something from it, its already available.
2. Include the styles for Static CMS at the very end of your page. Right now the two css rules you have there have the same [specificity](https://www.w3schools.com/css/css_specificity.asp), so it defaults to what was included last (or most recent). This appears to be your tailwind reset css.
