### ISSUE TITLE
Changes an image does not get registered as a change

### ISSUE THREAD

**Issue by Pension-Almhof** [StaticJsCMS/static-cms#944]
Changing an image does not trigger the Publish button to be activated. First some textfield has to be changed (adding a charachter and removing it does the job).

**Comment by denyskon** [comment]
It's the same with booleans for me.....

**Comment by kara-todd** [comment]
I'm also seeing this with object fields.

**Steps to reproduce:**
- Load the dev environment (npm run dev)
- Go to `/collections/widgets/entries/objects`
- Under `Required Validation` change the value of the `Author` field to any string
- Click out of the field

**Expected results**
Publish button is enabled 

**Acutal results**
The changed text appears in the preview, but the publish button remains grayed out.

**Comment by KaneFreeman** [comment]
This should be fixed in `v3.3.11`.
