### ISSUE TITLE
The markdown for the "hint" option of the widgets does not work

### ISSUE THREAD

**Issue by lorensansol** [StaticJsCMS/static-cms#953]
Hi! In [Common widget options](https://www.staticcms.org/docs/widgets#common-widget-options), in `hint` option say:

> [...] Accepts markdown for bold, italic, strikethrough, and links.

But this not work. Example with links:

![Captura de pantalla 2023-10-27 a las 16 26 27](https://github.com/StaticJsCMS/static-cms/assets/67113672/d1d6d9fa-d438-4a10-9735-3d69a450c8d5)

Also happens with bold, italic and strikethrough.

**Comment by KaneFreeman** [comment]
This is fixed in `v3.4.2`.
