### ISSUE TITLE
show current version

### ISSUE THREAD

**Issue by whysthatso** [StaticJsCMS/static-cms#959]
it's a common grievance for me to ensure what exact version of a library i am actually running, especially when loaded with optimistic version constraints from a cdn.

a really simple solution is to blend in a very small footer addition with the current version, or if this is too distracting, just as a comment in the html file.

**Comment by KaneFreeman** [comment]
The current version is printed out in the developer console.

![image](https://github.com/StaticJsCMS/static-cms/assets/1388138/514a13e8-6292-40ec-8e70-0ea8284b04d1)

**Comment by denyskon** [comment]
@KaneFreeman Is it possible that it does not happen when using the CDN version (@staticcms/app)? At least for me the first message I get in the console is that mount event

**Comment by KaneFreeman** [comment]
I will look into that.

**Comment by whysthatso** [comment]
confirmed, i don't see this line in the dev console

**Comment by KaneFreeman** [comment]
This is fixed in `v3.4.3`. You can see it in action here: https://eleventy.staticcms.org/admin/

**Comment by whysthatso** [comment]
yep, works for me. thank you
