### ISSUE TITLE
Open link in new Tab

### ISSUE THREAD

**Issue by FutureBuddha** [StaticJsCMS/static-cms#975]
Hi there,

it would be great if you add a option to add target="_blank" in the links in the content, so that the link open up in a new tab.
Also it would be nice to add some links to pictures with the same function.

Thank you very much in advance.

**Comment by KaneFreeman** [comment]
Are you talking about in the markdown editor? Where are you trying to click the links that they are not opening in a new tab?

**Comment by FutureBuddha** [comment]
Yes, exactly. I used the Nebulix theme with your CMS https://github.com/unfolding-io/nebulix. However, when I try something like [Linktext](https://chat.openai.com/c/URL){target="_blank"}, errors occur in Astro. Even when I change the editor field to rich text, it doesn't display it correctly.

At the moment, I can only open a link in a new tab when I paste it directly into the markdown editor like this: <a href="https://github.com" target="_blank">Github</a>. While this works, it's not an ideal solution.
