### ISSUE TITLE
YAML Formatter Options

### ISSUE THREAD

**Issue by KaneFreeman** [StaticJsCMS/static-cms#976]
Hello! I would like to customize the criteria with which to save YAML and Markdown files:

- Literal text blocks instead of folded ones
- Text strings preferably without quotes, but with single quotes if necessary
- Single line text strings without line breaks (as if the width of the document were infinite)
- One less level of indentation in arrays

Would it be possible to do this online and save all compilation?

_Originally posted by @lorensansol in https://github.com/StaticJsCMS/static-cms/discussions/974_

**Comment by KaneFreeman** [comment]
@lorensansol this is available in `v4.0.0-beta.3`

**Comment by lorensansol** [comment]
Marvelous! 🤩

But the truth is that I don't understand how or where to use it.

Would it be too much to ask for a small example without compilation? (I found a [`yaml` CDN](https://www.jsdelivr.com/package/npm/yaml))

**Comment by KaneFreeman** [comment]
You can find an example here in the docs: https://next.staticcms.org/docs/configuration-options#yaml-options
