### ISSUE TITLE
[Docs] client side error when typing "["

### ISSUE THREAD

**Issue by locomoco28** [StaticJsCMS/static-cms#978]
Typing `[` in the input field on the website returns a client side error.

```
SyntaxError: unterminated character class
    NextJS 20
framework-19f3649580393c10.js:9:69814
```

You can type `]` and then move to the left and type `[`
Using normal brackets `(`/`)` both crash, no matter which one you type first

**Comment by KaneFreeman** [comment]
This is now resolved.
