### ISSUE TITLE
Unable to insert relative or root-relative links

### ISSUE THREAD

**Issue by torce** [StaticJsCMS/static-cms#985]
Hello,
When I insert a relative or root-relative link, the media folder is prepended to the link href.
Absolute links work just fine, but are less useful if the site is used in several subdomains.

[Screencast from 16-11-23 08:28:42.webm](https://github.com/StaticJsCMS/static-cms/assets/3646997/6a5cdc88-8e7e-46f0-b453-f03448f16fd7)

Thanks for your work in this fantastic CMS :smile:

**Comment by KaneFreeman** [comment]
This is fixed in `v3.4.6`.
