### ISSUE TITLE
Error: '.properties.search.type' must be string

### ISSUE THREAD

**Issue by almereyda** [StaticJsCMS/static-cms#987]
I have set `search: true` in `config.yml`, as per the documentation entry, and the browser console throws:

    Error: '.properties.search.type' must be string

This is because the schema says it is a string.

https://github.com/StaticJsCMS/static-cms/blob/f90f805a246cac47a3ce111ecdaa3e30c0179655/packages/core/src/constants/configSchema.tsx#L422

I like to copy default values in configuration files, so I know I have the choice to change them. Maybe nobody ever happened to check?

The repository in question is https://github.com/ecobytes/the.compost.place/tree/main/static/admin

Workaround appears to just leave the field out for now.

Are there tests for this?

**Comment by KaneFreeman** [comment]
There are no tests for the config schema, but that probably should be.

**Comment by KaneFreeman** [comment]
This is fixed in `v3.4.6`.

**Comment by almereyda** [comment]
Thank you.
